(lang dune 3.7)

(name secwasm)

(generate_opam_files true)

(package
 (name secwasm)
 (depends ocaml dune bisect_ppx))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
